### ISSUE TITLE
Integrate in iOS swift through SPM

### ISSUE THREAD

**Issue by Adityag4234** [hCaptcha/HCaptcha-ios-sdk#104]
How to integrate in iOS project through SPM?

**Comment by CAMOBAP** [comment]
@Adityag4234 this should be straightforward, just add a `.package` to the dependencies list like this:

```
let package = Package(
    name: "MyPackage",
    dependencies: [
        ...
        // this line below
        .package(url: "https://github.com/hCaptcha/HCaptcha-ios-sdk", from: .upToNextMajor(from:"2.3.3")),
    ],
    targets: [
        ...
    ]
)
```

More info in SPM documentation https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#defining-dependencies

Feel free to contact us if you have any issues with this

**Comment by CAMOBAP** [comment]
@Adityag4234 feel free to reopen it at any time if you still have issues
