### ISSUE TITLE
HCaptcha Is Not Shown First Time, It Succeeds Seamlessly 🐛 

### ISSUE THREAD

**Issue by markoNazmy** [hCaptcha/HCaptcha-ios-sdk#117]
## Bug description
I'm using HCaptcha to save my app from being attacked with some requests so I need it to challenge our users every time, but the behaviour is when I do the captcha test for the first time, it's not shown, if I back on the same run and I clicked the button that launches the captcha again I will see it work, while the first time captcha returns valid token without running the manual quiz .

## To Reproduce

1. run the app with valid certificate on real devices, preferably from TestFlight.
2. open your app and run the captcha make it pass for one time at least.
3. close the app.
4. run again and try to run the captcha quiz it will be seamless and you will get token but not quizes.
5. back and click on your button that launches the captcha it will be shown normally.

## Expected behavior
I need the test to be available every time I launch the captcha.

## Additional context

- I tried the reset function but it does nothing.
- My app Configuration is always challenge.

**Comment by e271828-** [comment]
@markoNazmy This is a configuration-related behavior. Please email support@hcaptcha.com for guidance.
