### ISSUE TITLE
Double-check manifest requirements

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/HCaptcha-ios-sdk#128]
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by CAMOBAP** [comment]
A couple of examples found for other SDK/Packages
- https://github.com/protocolbuffers/protobuf/commit/684660f025703afbc4775dedf9a0bf732b696cf1#diff-6d123ae8ab04eee632cc6c18a31d71271ad217595dcd4401c63875b4b5c0e226
- https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/PrivacyInfo.xcprivacy

Based on official information:
- per https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api - `NSPrivacyAccessedAPITypes` will be empty because the SDK doesn't use API listed there
- SDK doesn't track users, at least per definitions in https://developer.apple.com/app-store/user-privacy-and-data-use/
- per https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests we only use `NSPrivacyCollectedDataTypeOtherDiagnosticData`

- CocoaPods support ticket - https://github.com/CocoaPods/CocoaPods/issues/10325
- [No dedicated tickets for Carthage](https://github.com/Carthage/Carthage/issues?q=is%3Aissue+privacy+is%3Aopen) because `PrivacyInfor.xcprivacy` simply can be added as a resource to target in `HCaptcha-Carthage.xcodeproj`
- SPM approach https://forums.developer.apple.com/forums/thread/742527

PR on the way

**Comment by sa4044** [comment]
> https://developer.apple.com/support/third-party-SDK-requirements/
