### ISSUE TITLE
Revisit differences between Android and iOS SDK

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/HCaptcha-ios-sdk#129]
Android behavior has several advances that iOS SDK still does not have
- `markUsed` for a token that will prevent expired errors from being fired
- Remove `webView` automatically once a token is generated or an error happens

cc @e271828-

**Comment by e271828-** [comment]
@CAMOBAP yes, we should duplicate those features for iOS as well.

**Comment by e271828-** [comment]
Also passive/ invisible support as in Android.

**Comment by CAMOBAP** [comment]
Last point left:
- [ ] Remove webView automatically once a token is generated or an error happens

**Comment by CAMOBAP** [comment]
> Last point left:
> 
> * [ ]  Remove webView automatically once a token is generated or an error happens

closed as non relevant
