### ISSUE TITLE
Add a way to force the manager to call the configureWebView method

### ISSUE THREAD

**Issue by pblanchetteNventive** [hCaptcha/HCaptcha-ios-sdk#138]
## Feature description
Add a method to explicitly allow the user of the package to redraw the webview. This would allow a user to update the webviews bounds depending on the state of the hcapcha challenge.

Currently AFAIK, the webview can only be sized at init or when reset(), I'd like to change the webview bounds when the challenge is passed with success.

## Requirements
The feature will be complete when these things are done:
- [x] We can explicitly reset the webview's bounds without reloading the webview, effectively bypassing the configureWebViewDispatchToken

## Other comments (optional)
I'm currently bypassing this locally by adding a reload method to the Hcapcha class, which calls a forceRedrawWebView to the Hcapcha manager, which then call the configureWebview closure passed at initialisation time, but I'd like this to be in the source package.

**Comment by e271828-** [comment]
@pblanchetteNventive would you like to PR your local change?

**Comment by pblanchetteNventive** [comment]
> @pblanchetteNventive would you like to PR your local change?

Done

**Comment by WilliamJose-SimardTouzet** [comment]
Hi, I see this as been merged in #140. Do you have an idea of when this could be in a release? Thank you

**Comment by e271828-** [comment]
This has been released as 2.6.2
