### ISSUE TITLE
How to force visual challenge?

### ISSUE THREAD

**Issue by aidano** [hCaptcha/HCaptcha-ios-sdk#169]
We want to be able to always show the visual challenge in certain environments for QA purposes. How can this be achieved?

**Comment by CAMOBAP** [comment]
@aidano You can use '00000000-0000-0000-0000-000000000000' as `siteKey`

**Comment by aidano** [comment]
Great - thank you! Does this key otherwise function the same as the pro account test key?

**Comment by CAMOBAP** [comment]
@aidano Actually the right way will be to create a sitekey and set it to Always Challenge, the suggestion above isn't quite correct
