### ISSUE TITLE
Support passing standard `theme` and `customTheme` object to init

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#27]
## Feature description
Add support for JS SDK's theme features.

## Requirements
The feature will be complete when these things are done:

- [ ] Can pass `theme` option into init. 

Example string values: `light` `dark` etc: https://docs.hcaptcha.com/configuration#themes

- [ ] Can pass `customTheme` object into init.

Usage looks like:

1. passing a value in init causes it to add `custom=true` to `api.js` params.

2. render function is updated to execute following this pattern:

```
    var onLoad = function() {
      hcaptcha.render("h-captcha", {
        "sitekey": "<sitekey>",
        "theme"  : {
          primary: {
            main: "#00FF00"
          },
          text: {
            heading: "#454545",
            body   : "#8C8C8C"
          }
        }
      });
    };
```

- [ ] README updated to describe usage.

## Other comments

1. Custom themes will only work on an enabled enterprise sitekey
2. We probably want to specify that `customTheme` is provided to init as JSON for everyone's sanity.

**Comment by CAMOBAP** [comment]
@e271828- maybe you can provide an example value for `customTheme` (didn't manage to find it in documentation)?

**Comment by e271828-** [comment]
> {
>           primary: {
>             main: "#00FF00"
>           },
>           text: {
>             heading: "#454545",
>             body   : "#8C8C8C"
>           }
>         }

**Comment by CAMOBAP** [comment]
I think it will be nice to do some validation of `customTheme`.

If it will be passed as a JSON string there is no problem, but if it will be passed as a JS object (as above) we will need to execute it as JS i.e. run some simple JS program with `JavaScriptCore` Framework for example

Summary, I see three options here:
1. We force users to send us valid JSON, easy validation
2. We allow to pass both JSON string JS object, and do a bit of advance validation with `JavaScriptCore`
3. Don't do any validation

@e271828- how do you think?

**Comment by CAMOBAP** [comment]
Checklist:
 - [x] Can pass `theme` option into init.
 - [x] Can pass `customTheme` option into init.
 - [x] Validate input against `JSON` rules and `JSObject` rules 
 - [x] Pass a value in init causes it to add custom=true to api.js params.
 - [x] Pass theme to html as template param 
 - [x] Automation tests
 - [ ] Swiftlint issues because HCaptcha.swift becomes over 400 lines - in progress

**Comment by CAMOBAP** [comment]
@e271828- ready for review https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/30
