### ISSUE TITLE
Switch deploy/release to fire on workflow run of Github Action

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#28]
## Feature description
Add a workflow that triggers the deploy/release flow from master.

## Requirements
The feature will be complete when these things are done:
- [x] CocoaPods release is automated
- [x] Carthage import is validated
- [x] SPM import is validated

**Comment by CAMOBAP** [comment]
@e271828- could you please add cocoapods token in repo settings as secret with name `COCOAPODS_TRUNK_TOKEN`

**Comment by CAMOBAP** [comment]
@e271828- the list in the topic is ready https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/31
