### ISSUE TITLE
sdk errors

### ISSUE THREAD

**Issue by evgeniy-bizhanov** [hCaptcha/HCaptcha-ios-sdk#41]
why iOS sdk errors different from android sdk errors? I need to handle for example this one

```
    /**
     * Internet connection is missing.
     *
     * Make sure AndroidManifest requires internet permission: {@code {@literal <}uses-permission android:name="android.permission.INTERNET" /{@literal >}}
     */
    NETWORK_ERROR(7, "No internet connection"),

    /**
     * hCaptcha session timed out either the token or challenge expired
     */
    SESSION_TIMEOUT(15, "Session Timeout"),

    /**
     * Rate limited due to too many tries.
     */
    RATE_LIMITED(31, "Rate Limited"),
```
but instead it stays at the JS log level

**Comment by CAMOBAP** [comment]
Some details:
 - code: `15`, Android: `SESSION_TIMEOUT`, iOS: `.responseExpired`
 - code: `31`, Android: `RATE_LIMITED`, iOS: `.failedRender`
 - code: `7`, Android: `NETWORK_ERROR ` iOS: No dedicated error, but `.failedRender` will be thrown

What we can do to improve error handling:
1. harmonize error naming, to use the same naming i.e. Android: `SESSION_TIMEOUT`, iOS: `.sessionTimeout`
1. add network error (no internet) handling for iOS (probably with `navigator.onLine` callback https://caniuse.com/?search=online)

@evgeniy-bizhanov @e271828- how do you think about those options?
