### ISSUE TITLE
Question on configureWebView and view.bounds

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/HCaptcha-ios-sdk#46]
Question received:

> configureWebView() is required to be called, but does it require the webview to be set to the view.bounds? When setting it to view.bounds, it seems that even after the invisible challenge is completed, the webview doesn't go away resulting in a blank screen on top of the underlying view. When setting it to CGRect.zero, it doesn't block the view at all, so can we do that?

### Action items

 - [x] check if `webview.bounds = view.bounds` required
 - [x] check issue with webview (doesn't go away)
 - [x] check proposed workaround

**Comment by e271828-** [comment]
Let's make sure to clearly document this in the README, at least.

**Comment by CAMOBAP** [comment]
@e271828-

https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/48 - done
