### ISSUE TITLE
Is there any plan to support swift package manager?

### ISSUE THREAD

**Issue by alikiran** [hCaptcha/HCaptcha-ios-sdk#5]
Swift Package gets popular day by day and in our case, it's the default dependency management tool. It would be nice to have SPM integration possibility

**Comment by e271828-** [comment]
Sure, PRs welcome :)

**Comment by CAMOBAP** [comment]
In progress, almost done, Currently I debugging test target which will be managed by SPM, (I would say %60-70 ready)

Draft PR pushed https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/26
