### ISSUE TITLE
Query: adding hCaptcha WkWebview to a container with a blur background

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#50]
Report: when adding the hCaptcha WkWebview to a container with a blur background the Webview is not loading sometimes.

Snippet:

```
hcaptcha?.configureWebView { [weak self] webview in
            webview.frame = self?.captchaContainerView.bounds ?? CGRect.zero
        }
        
        hcaptcha?.validate(on: captchaContainerView,
                           resetOnError: true,
                           completion: { [weak self] result in
            guard let self = self else {
                completionHandler(false, nil, ZError.default)
                return
            }
            
            self.captchaBackgroundView.zHide()
            self.captchaBackgroundView.removeFromSuperview()
            
            self.hcaptcha?.stop()
            if let data = try? result.dematerialize() {
                ZLog.i(data)
                completionHandler(true, data, nil)
            }
            else {
                completionHandler(false, nil, ZError.default)
            }
        })
```

**Comment by CAMOBAP** [comment]
In progress

**Comment by CAMOBAP** [comment]
I think I have reproduced the issue, but I'm not 100% sure

Here is what I did:
 - Created ContainerView in Xcode Interface Builder
 - Created `UIVisualEffectView` for blur effect

#### Screenshot from `Debug View Hierarchy`
<img width="299" alt="runtime" src="https://user-images.githubusercontent.com/2169738/156796096-a3e05e32-890e-4d06-abad-2bbb25827ba2.png">

#### Screenshot from Interface Builder
<img width="296" alt="ui_builder" src="https://user-images.githubusercontent.com/2169738/156796101-5c5fd0a2-911c-4c23-a443-7f832bedf616.png">

#### Result

The WebView looks gray
<img width="150" alt="simulator" src="https://user-images.githubusercontent.com/2169738/156796411-0ed8fc22-aa34-43a9-ae27-493f6e355af3.png">

@e271828-  can we somehow confirm that this is the issue which client observe? Maybe we can ask for some screenshots?

**Comment by CAMOBAP** [comment]
I have found that issue happens if we are trying to add `WKWebView` to subview of `UIVisualEffectView` or its child (**_red_** rectangle on the screenshot below)

As workaround we may use parent view of `UIVisualEffectView`, the **_green_** rectangle on the screenshot below

<img width="384" alt="Screen Shot 2022-03-08 at 7 27 36 AM" src="https://user-images.githubusercontent.com/2169738/157179754-41f073e2-cfdf-4cfc-8596-814e0996661b.png">
`

P.S. Still researching the root of the issue, and workaround to allow placing `WKWebView` on top of `UIVisualEffectView`

**Comment by CAMOBAP** [comment]
**Update**

Per [Apple's documentation](https://developer.apple.com/documentation/uikit/uivisualeffectview#overview):

> After you add the visual effect view to the view hierarchy, add any subviews to the [contentView](https://developer.apple.com/documentation/uikit/uivisualeffectview/1615068-contentview) property of the visual effect view. **Do not add subviews directly to the visual effect view itself.**

Also, the same issue described on SO https://stackoverflow.com/questions/46355872/warning-from-ios-do-not-add-subviews-directly-to-the-visual-effect-view-itself

So instead passing `visualEffectView` (instance of `UIVisualEffectView`), pass `visualEffectView.contentView`
