### ISSUE TITLE
Support for Apple Private Access Tokens

### ISSUE THREAD

**Issue by akaDuality** [hCaptcha/HCaptcha-ios-sdk#82]
## Feature description
Apple introduced support for Private Access Token for iOS 16 that allows to verify users without captcha's input. [The support can be implemented on captcha's side](https://developer.apple.com/videos/play/wwdc2022/10077/).

## Requirements
The feature will be complete when these things are done:
- [ ] hCaptcha can receive token request from our server
- [ ] hCaptcha issues the token 
- [ ] out server verify token

<img width="765" alt="Screen Shot 2022-06-22 at 10 13 54" src="https://user-images.githubusercontent.com/3120680/174949641-38b3b372-aa8c-4745-838f-1562ca1ff391.png">

**Comment by e271828-** [comment]
@akaDuality this feature doesn't require mobile SDK changes: it's basically a minor tweak to our existing Privacy Pass support, which is mainly a backend change. We've announced support here: https://www.hcaptcha.com/post/announcing-support-for-private-access-tokens
