### ISSUE TITLE
Review Crit/Major code smells from Sonar

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#86]
See if there are any items we want to address. PR quick ones, create issue for anything more involved.

- [ ] https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=hCaptcha_HCaptcha-ios-sdk

- [ ] https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=hCaptcha_HCaptcha-ios-sdk

**Comment by CAMOBAP** [comment]
Also I think we should run sonarqube on CI (to use our own configs) https://docs.fastlane.tools/actions/sonar/

**Comment by e271828-** [comment]
It was disappointing when I set it up on Android CI, seemed pretty buggy. We can try it and see if iOS is any better. Might switch to a different product though.

**Comment by CAMOBAP** [comment]
Could you please clarify what you mean?

AFAIK Sonar is just a faced which runs a lot of different scanners under the hood, and provide a nice dashboard to control technical debt

We are run the same tools (like swiftlint, and pod lint) so we just need to feed sonar.properties with correct paths to our configs for those tools

**Comment by e271828-** [comment]
> Could you please clarify what you mean?
> 
> AFAIK Sonar is just a faced which runs a lot of different scanners under the hood, and provide a nice dashboard to control technical debt
> 
> We are run the same tools (like swiftlint, and pod lint) so we just need to feed sonar.properties with correct paths to our configs for those tools

Their remote scanner seems more reliable than when it is integrated in CI. You can take a look at the Android test runs to see, or https://community.sonarsource.com/t/incorrect-coverage-report-unchanged-lines-of-code-in-java-ci-android-gradle/67997/14
