### ISSUE TITLE
Slow init because of DebugInfo

### ISSUE THREAD

**Issue by benqo** [hCaptcha/HCaptcha-ios-sdk#89]
There seems to be a delay on init, and it blocks the thread, looks like it is this:
`public let json: String = HCaptchaDebugInfo.buildDebugInfoJson()`

If I disable the `buildDebugInfoJson()` then the init is instant.

I tried multiple versions, and all work the same. It is especially apparent on the simulator.

**Comment by benqo** [comment]
I guess this is the fix https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/88/commits ?

**Comment by e271828-** [comment]
Yes, will be resolved shortly.
